CREATE TABLE [dbo].[CfgParamInicioUsuarioCosmos] (
    [ParamInicioUsuarioCosmosID]               INT      IDENTITY (1, 1) NOT NULL,
    [PpalAreaIDInicio]                         INT      NOT NULL,
    [PpalCentroCostoIDInicio]                  INT      NOT NULL,
    [EspCiudadIDInicio]                        INT      NOT NULL,
    [PpalConceptoEgresoIDInicio]               INT      NOT NULL,
    [PpalConceptoIngresoIDInicio]              INT      NOT NULL,
    [EspEstadoIDInicio]                        INT      NOT NULL,
    [AuxEstadoCivilIDInicio]                   INT      NOT NULL,
    [CfgEstatusClienteIDInicio]                INT      NOT NULL,
    [CfgEstatusContactoPersonalIDInicio]       INT      NOT NULL,
    [CfgEstatusDocumentoIDInicio]              INT      NOT NULL,
    [CfgEstatusPersonalIDInicio]               INT      NOT NULL,
    [CmpEstatusProveedorIDInicio]              INT      NOT NULL,
    [CmpEstatusRepresentanteProveedorIDInicio] INT      NOT NULL,
    [CfgFamiliaProductoIDInicio]               INT      NOT NULL,
    [AuxFormaPagoIDInicio]                     INT      NOT NULL,
    [AuxGiroEmpresaIDInicio]                   INT      NOT NULL,
    [AuxHorarioPersonalIDInicio]               INT      NOT NULL,
    [AuxIdiomaIDInicio]                        INT      NOT NULL,
    [AuxMarcaIDInicio]                         INT      NOT NULL,
    [AuxMedioContactoIDInicio]                 INT      NOT NULL,
    [EspMunicipioIDInicio]                     INT      NOT NULL,
    [EspPaisIDInicio]                          INT      NOT NULL,
    [AuxProfesionIDInicio]                     INT      NOT NULL,
    [SistemaSexoIDInicio]                      INT      NOT NULL,
    [CfgTipoClienteIDInicio]                   INT      NOT NULL,
    [CfgTipoContactoPersonalIDInicio]          INT      NOT NULL,
    [CfgTipoDomicilioIDInicio]                 INT      NOT NULL,
    [CfgTipoFechaIDInicio]                     INT      NOT NULL,
    [CfgTipoHorarioIDInicio]                   INT      NOT NULL,
    [CfgTipoMailIDInicio]                      INT      NOT NULL,
    [CfgTipoProductoIDInicio]                  INT      NOT NULL,
    [CmpTipoProveedorIDInicio]                 INT      NOT NULL,
    [CfgTipoRepresentanteClienteIDInicio]      INT      NOT NULL,
    [CmpTipoRepresentanteProveedorIDInicio]    INT      NOT NULL,
    [CfgTipoTelefonoIDInicio]                  INT      NOT NULL,
    [AuxUnidadIDInicio]                        INT      NOT NULL,
    [AuxVinculoIDInicio]                       INT      NOT NULL,
    [AuxZonaIDInicio]                          INT      NOT NULL,
    [EmpresaID]                                INT      NOT NULL,
    [FechaInicio]                              DATETIME NOT NULL,
    [CfgUsoTelefonoIDInicio]                   INT      NOT NULL,
    [PpalSucursalIDInicio]                     INT      NOT NULL,
    CONSTRAINT [PK_CfgParamInicioUsuarioCosmos2] PRIMARY KEY CLUSTERED ([ParamInicioUsuarioCosmosID] ASC),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_AuxEstadoCivil] FOREIGN KEY ([AuxEstadoCivilIDInicio]) REFERENCES [dbo].[AuxEstadoCivil] ([AuxEstadoCivilID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_AuxFormaPago] FOREIGN KEY ([AuxFormaPagoIDInicio]) REFERENCES [dbo].[AuxFormaPago] ([AuxFormaPagoID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_AuxHorarioPersonal] FOREIGN KEY ([AuxHorarioPersonalIDInicio]) REFERENCES [dbo].[AuxHorarioPersonal] ([AuxHorarioPersonalID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_AuxIdioma] FOREIGN KEY ([AuxIdiomaIDInicio]) REFERENCES [dbo].[AuxIdioma] ([AuxIdiomaID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_AuxMarca] FOREIGN KEY ([AuxMarcaIDInicio]) REFERENCES [dbo].[AuxMarca] ([AuxMarcaID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_AuxMedioContacto] FOREIGN KEY ([AuxMedioContactoIDInicio]) REFERENCES [dbo].[AuxMedioContacto] ([AuxMedioContactoID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_AuxProfesion] FOREIGN KEY ([AuxProfesionIDInicio]) REFERENCES [dbo].[AuxProfesion] ([AuxProfesionID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_AuxUnidad] FOREIGN KEY ([AuxUnidadIDInicio]) REFERENCES [dbo].[AuxUnidad] ([AuxUnidadID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_AuxVinculo] FOREIGN KEY ([AuxVinculoIDInicio]) REFERENCES [dbo].[AuxVinculo] ([AuxVinculoID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_AuxZona] FOREIGN KEY ([AuxZonaIDInicio]) REFERENCES [dbo].[AuxZona] ([AuxZonaID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_CfgEstatusCliente] FOREIGN KEY ([CfgEstatusClienteIDInicio]) REFERENCES [dbo].[CfgEstatusCliente] ([CfgEstatusClienteID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_CfgEstatusContactoPersonal] FOREIGN KEY ([CfgEstatusContactoPersonalIDInicio]) REFERENCES [dbo].[CfgEstatusContactoPersonal] ([CfgEstatusContactoPersonalID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_CfgEstatusDocumento] FOREIGN KEY ([CfgEstatusDocumentoIDInicio]) REFERENCES [dbo].[CfgEstatusDocumento] ([CfgEstatusDocumentoID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_CfgEstatusPersonal] FOREIGN KEY ([CfgEstatusPersonalIDInicio]) REFERENCES [dbo].[CfgEstatusPersonal] ([CfgEstatusPersonalID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_CfgFamiliaProducto] FOREIGN KEY ([CfgFamiliaProductoIDInicio]) REFERENCES [dbo].[CfgFamiliaProducto] ([CfgFamiliaProductoID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_CfgParamInicioUsuarioCosmos] FOREIGN KEY ([ParamInicioUsuarioCosmosID]) REFERENCES [dbo].[CfgParamInicioUsuarioCosmos] ([ParamInicioUsuarioCosmosID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_CfgParamInicioUsuarioCosmos2] FOREIGN KEY ([PpalAreaIDInicio]) REFERENCES [dbo].[PpalArea] ([PpalAreaID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_CfgTipoCliente] FOREIGN KEY ([CfgTipoClienteIDInicio]) REFERENCES [dbo].[CfgTipoCliente] ([CfgTipoClienteID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_CfgTipoContactoPersonal] FOREIGN KEY ([CfgTipoContactoPersonalIDInicio]) REFERENCES [dbo].[CfgTipoContactoPersonal] ([CfgTipoContactoPersonalID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_CfgTipoDomicilio] FOREIGN KEY ([CfgTipoDomicilioIDInicio]) REFERENCES [dbo].[CfgTipoDomicilio] ([CfgTipoDomicilioID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_CfgTipoFecha] FOREIGN KEY ([CfgTipoFechaIDInicio]) REFERENCES [dbo].[CfgTipoFecha] ([CfgTipoFechaID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_CfgTipoHorario] FOREIGN KEY ([CfgTipoHorarioIDInicio]) REFERENCES [dbo].[CfgTipoHorario] ([CfgTipoHorarioID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_CfgTipoMail] FOREIGN KEY ([CfgTipoMailIDInicio]) REFERENCES [dbo].[CfgTipoMail] ([CfgTipoMailID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_CfgTipoProducto] FOREIGN KEY ([CfgTipoProductoIDInicio]) REFERENCES [dbo].[CfgTipoProducto] ([CfgTipoProductoID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_CfgTipoRepresentanteCliente] FOREIGN KEY ([CfgTipoRepresentanteClienteIDInicio]) REFERENCES [dbo].[CfgTipoRepresentanteCliente] ([CfgTipoRepresentanteClienteID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_CfgTipoTelefono] FOREIGN KEY ([CfgTipoTelefonoIDInicio]) REFERENCES [dbo].[CfgTipoTelefono] ([CfgTipoTelefonoID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_CfgUsoTelefono] FOREIGN KEY ([CfgUsoTelefonoIDInicio]) REFERENCES [dbo].[CfgUsoTelefono] ([CfgUsoTelefonoID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_CmpEstatusProveedor] FOREIGN KEY ([CmpEstatusProveedorIDInicio]) REFERENCES [dbo].[CmpEstatusProveedor] ([CmpEstatusProveedorID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_CmpEstatusRepresentanteProveedor] FOREIGN KEY ([CmpEstatusRepresentanteProveedorIDInicio]) REFERENCES [dbo].[CmpEstatusRepresentanteProveedor] ([CmpEstatusRepresentanteProveedorID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_CmpTipoProveedor] FOREIGN KEY ([CmpTipoProveedorIDInicio]) REFERENCES [dbo].[CmpTipoProveedor] ([CmpTipoProveedorID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_CmpTipoRepresentanteProveedor] FOREIGN KEY ([CmpTipoRepresentanteProveedorIDInicio]) REFERENCES [dbo].[CmpTipoRepresentanteProveedor] ([CmpTipoRepresentanteProveedorID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_EspCiudad] FOREIGN KEY ([EspCiudadIDInicio]) REFERENCES [dbo].[EspCiudad] ([EspCiudadID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_EspEstado] FOREIGN KEY ([EspEstadoIDInicio]) REFERENCES [dbo].[EspEstado] ([EspEstadoID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_EspMunicipio] FOREIGN KEY ([EspMunicipioIDInicio]) REFERENCES [dbo].[EspMunicipio] ([EspMunicipioID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_EspPais] FOREIGN KEY ([EspPaisIDInicio]) REFERENCES [dbo].[EspPais] ([EspPaisID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_PpalCentroCosto] FOREIGN KEY ([PpalCentroCostoIDInicio]) REFERENCES [dbo].[PpalCentroCosto] ([PpalCentroCostoID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_PpalConceptoEgreso] FOREIGN KEY ([PpalConceptoEgresoIDInicio]) REFERENCES [dbo].[PpalConceptoEgreso] ([PpalConceptoEgresoID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_PpalConceptoIngreso] FOREIGN KEY ([PpalConceptoIngresoIDInicio]) REFERENCES [dbo].[PpalConceptoIngreso] ([PpalConceptoIngresoID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_PpalSucursal] FOREIGN KEY ([PpalSucursalIDInicio]) REFERENCES [dbo].[PpalSucursal] ([PpalSucursalID]),
    CONSTRAINT [FK_CfgParamInicioUsuarioCosmos_SistemaSexo] FOREIGN KEY ([SistemaSexoIDInicio]) REFERENCES [dbo].[SistemaSexo] ([SexoID])
);

