CREATE TABLE [dbo].[EspPersona] (
    [EspPersonaID]              INT            IDENTITY (1, 1) NOT NULL,
    [FisicaMoral]               CHAR (1)       NOT NULL,
    [NombreComercial]           NVARCHAR (120) NOT NULL,
    [RazonSocial]               NVARCHAR (120) NOT NULL,
    [Nombre]                    NVARCHAR (35)  NOT NULL,
    [ApellidoPaterno]           NVARCHAR (30)  NOT NULL,
    [ApellidoMaterno]           NVARCHAR (30)  NOT NULL,
    [RFC]                       NVARCHAR (13)  NOT NULL,
    [CURP]                      NVARCHAR (18)  NOT NULL,
    [SistemaSexoID]             INT            NOT NULL,
    [FechaNacimiento]           DATE           NOT NULL,
    [EspCiudadNacimientoID]     INT            NOT NULL,
    [AuxEstadoCivilID]          INT            NOT NULL,
    [CasadoCivil]               BIT            NOT NULL,
    [CasadoIglesia]             BIT            NOT NULL,
    [Iniciales]                 VARCHAR (6)    NOT NULL,
    [SobreNombre]               VARCHAR (25)   NOT NULL,
    [NombreCorto]               NVARCHAR (25)  CONSTRAINT [DF_Persona_NombreCorto] DEFAULT ('') NOT NULL,
    [EspDomicilioIDFacturacion] INT            NULL,
    [SATRegimenFiscalID]        INT            NULL,
    CONSTRAINT [PK_EspPersona] PRIMARY KEY CLUSTERED ([EspPersonaID] ASC),
    CONSTRAINT [FK_EspPersona_EspDomicilio] FOREIGN KEY ([EspDomicilioIDFacturacion]) REFERENCES [dbo].[EspDomicilio] ([EspDomicilioID]) ON DELETE SET NULL ON UPDATE SET NULL,
    CONSTRAINT [FK_EspPersona_SATRegimenFiscal] FOREIGN KEY ([SATRegimenFiscalID]) REFERENCES [dbo].[SATRegimenFiscal] ([SATRegimenFiscalID]) ON UPDATE SET NULL,
    CONSTRAINT [FK_EspPersona_SistemaSexo] FOREIGN KEY ([SistemaSexoID]) REFERENCES [dbo].[SistemaSexo] ([SexoID]),
    CONSTRAINT [FK_Persona_EspCiudad] FOREIGN KEY ([EspCiudadNacimientoID]) REFERENCES [dbo].[EspCiudad] ([EspCiudadID]),
    CONSTRAINT [FK_Persona_EstadoCivil] FOREIGN KEY ([AuxEstadoCivilID]) REFERENCES [dbo].[AuxEstadoCivil] ([AuxEstadoCivilID])
);

