//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cosmos.Api.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XPS13;Initial Catalog=DB_9E35A8_Cosmos;Integrated Security=True;Persi" +
            "st Security Info=False;Pooling=False;MultipleActiveResultSets=False;Connect Time" +
            "out=60;Encrypt=False;TrustServerCertificate=True")]
        public string Bk {
            get {
                return ((string)(this["Bk"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Data Source=sql5041.site4now.net;Initial Catalog=DB_9E35A8_Cosmos;User ID=DB_9E35A8_Cosmos_admin;Password=ncuatro100devData Source=sql5041.site4now.net;Initial Catalog=DB_9E35A8_Cosmos;User ID=DB_9E35A8_Cosmos_admin;Password=ncuatro100devData Source=sql5041.site4now.net;Initial Catalog=DB_9E35A8_Cosmos;User ID=DB_9E35A8_Cosmos_admin;Password=ncuatro100devData Source=sql5041.site4now.net;Initial Catalog=DB_9E35A8_Cosmos;User ID=DB_9E35A8_Cosmos_admin;Password=ncuatro100devData Source=sql5041.site4now.net;Initial Catalog=DB_9E35A8_Cosmos;User ID=DB_9E35A8_Cosmos_admin;Password=ncuatro100devData Source=sql5041.site4now.net;Initial Catalog=DB_9E35A8_Cosmos;User ID=DB_9E35A8_Cosmos_admin;Password=ncuatro100devData Source=sql5041.site4now.net;Initial Catalog=DB_9E35A8_Cosmos;User ID=DB_9E35A8_Cosmos_admin;Password=ncuatro100devData Source=sql5041.site4now.net;Initial Catalog=DB_9E35A8_Cosmos;User ID=DB_9E35A8_Cosmos_admin;Password=ncuatro100dev")]
        public string temp {
            get {
                return ((string)(this["temp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XPS13;Initial Catalog=DB_9E35A8_Cosmos;Integrated Security=True;Persi" +
            "st Security Info=False;Pooling=False;MultipleActiveResultSets=False;Connect Time" +
            "out=60;Encrypt=False;TrustServerCertificate=True")]
        public string Sistema {
            get {
                return ((string)(this["Sistema"]));
            }
        }
    }
}
