

CREATE PROCEDURE [dbo].[PpalRepresentanteProveedorDomicilio_Listado]
AS

SELECT  PpalRepresentanteProveedorDomicilioID,PpalRepresentanteProveedorID,EspDomicilioID,Comentario,Predeterminado,CfgTipoDomicilioID
FROM    PpalRepresentanteProveedorDomicilio