

CREATE PROCEDURE [dbo].[PpalRepresentanteProveedorDomicilio_ListadoRepresentanteProveedorID]
@PpalRepresentanteProveedorID INT
AS

SELECT  PpalRepresentanteProveedorDomicilioID,PpalRepresentanteProveedorID,EspDomicilioID
FROM    PpalRepresentanteProveedorDomicilio
WHERE   PpalRepresentanteProveedorID = @PpalRepresentanteProveedorID